# Generated by Django 5.0.2 on 2024-02-19 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('license_plate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DriverGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_vehicle_app.car')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_vehicle_app.cargroup')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_vehicle_app.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_vehicle_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriversGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_vehicle_app.driver')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_vehicle_app.drivergroup')),
            ],
        ),
    ]
