# Generated by Django 5.0.2 on 2024-02-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsgroup',
            name='name',
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cargroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
