# Generated by Django 5.0.2 on 2024-02-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_vehicle_app', '0002_remove_carsgroup_name_alter_car_license_plate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Car',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='carsgroup',
            old_name='Car',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='carsgroup',
            old_name='group',
            new_name='groupe',
        ),
        migrations.RenameField(
            model_name='driversgroup',
            old_name='group',
            new_name='groupe',
        ),
        migrations.RemoveField(
            model_name='driversgroup',
            name='name',
        ),
    ]
